[package]
name = "mros"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
multiboot2 = "0.1.0"
spin = "0.5.2"

[dependencies.lazy_static]
version = "1.0"
feature = ["spin_no_std"]

[dependencies.bitflags]
version = "2.4.1"
