[package]
name = "mros"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
spin = "0.5.2"
bitflags = "0.9.1"
multiboot2 = {version = "0.19.0", default-features = false}

[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]
